# Generated by Django 5.0.2 on 2026-05-29 11:57

import website.models
from django.db import migrations, models


def copy_featured_image_urls(apps, schema_editor):
    VisaRequirement = apps.get_model('website', 'VisaRequirement')
    for visa in VisaRequirement.objects.all():
        old_value = visa.featured_image
        if old_value and str(old_value).startswith('http'):
            visa.featured_image_url = str(old_value)
            visa.save(update_fields=['featured_image_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visarequirement',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='visarequirement',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Optional: use a URL if you are not uploading an image file', max_length=500),
        ),
        migrations.RunPython(copy_featured_image_urls, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='visarequirement',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Image shown on the visa card', null=True, upload_to=website.models.visa_image_path),
        ),
        migrations.AlterField(
            model_name='visarequirement',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF opened when visitors click the card', null=True, upload_to=website.models.visa_pdf_path),
        ),
    ]
