# Generated by Django 5.0.2 on 2026-06-08 13:01

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_package_image_and_price_filter'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='travelpackage',
                    name='full_description',
                    field=models.TextField(blank=True, help_text='Full description on the package detail page'),
                ),
                migrations.AddField(
                    model_name='travelpackage',
                    name='highlights',
                    field=models.TextField(blank=True, help_text='One highlight per line (shown on detail page)'),
                ),
                migrations.AddField(
                    model_name='travelpackage',
                    name='itinerary',
                    field=models.TextField(blank=True, help_text='One day per line, e.g. "Day 1: Arrival and hotel check-in"'),
                ),
                migrations.AddField(
                    model_name='travelpackage',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=220, unique=True),
                ),
                migrations.CreateModel(
                    name='PackageImage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('image', models.ImageField(blank=True, null=True, upload_to=website.models.package_gallery_path)),
                        ('external_image_url', models.URLField(blank=True, max_length=500)),
                        ('caption', models.CharField(blank=True, max_length=200)),
                        ('display_order', models.PositiveIntegerField(default=0)),
                        ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.travelpackage')),
                    ],
                    options={
                        'ordering': ['display_order'],
                    },
                ),
            ],
        ),
    ]
