# Generated by Django 5.0.2 on 2026-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_country_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='duration_ar',
            field=models.CharField(help_text='e.g. 7 Days / 6 Nights', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='duration_en',
            field=models.CharField(help_text='e.g. 7 Days / 6 Nights', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='duration_fr',
            field=models.CharField(help_text='e.g. 7 Days / 6 Nights', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='full_description_ar',
            field=models.TextField(blank=True, help_text='Full description on the package detail page', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='full_description_en',
            field=models.TextField(blank=True, help_text='Full description on the package detail page', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='full_description_fr',
            field=models.TextField(blank=True, help_text='Full description on the package detail page', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='highlights_ar',
            field=models.TextField(blank=True, help_text='One highlight per line (shown on detail page)', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='highlights_en',
            field=models.TextField(blank=True, help_text='One highlight per line (shown on detail page)', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='highlights_fr',
            field=models.TextField(blank=True, help_text='One highlight per line (shown on detail page)', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='itinerary_ar',
            field=models.TextField(blank=True, help_text='One day per line, e.g. "Day 1: Arrival and hotel check-in"', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='itinerary_en',
            field=models.TextField(blank=True, help_text='One day per line, e.g. "Day 1: Arrival and hotel check-in"', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='itinerary_fr',
            field=models.TextField(blank=True, help_text='One day per line, e.g. "Day 1: Arrival and hotel check-in"', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='name_ar',
            field=models.CharField(help_text='Package title shown on the website', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='name_en',
            field=models.CharField(help_text='Package title shown on the website', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='name_fr',
            field=models.CharField(help_text='Package title shown on the website', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='short_description_ar',
            field=models.TextField(help_text='Short description on the package card', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='short_description_en',
            field=models.TextField(help_text='Short description on the package card', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='short_description_fr',
            field=models.TextField(help_text='Short description on the package card', null=True),
        ),
        migrations.AddField(
            model_name='visarequirement',
            name='country_name_ar',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='visarequirement',
            name='country_name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='visarequirement',
            name='country_name_fr',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
