# Generated by Django 5.0.2 on 2026-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_testimonial_and_package_ar_overhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsimOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=30, unique=True)),
                ('monty_order_id', models.CharField(blank=True, db_index=True, max_length=24)),
                ('bundle_code', models.CharField(max_length=220)),
                ('bundle_name', models.CharField(blank=True, max_length=300)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_whatsapp', models.CharField(blank=True, max_length=40)),
                ('iccid', models.CharField(blank=True, max_length=24)),
                ('activation_code', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(blank=True, max_length=80)),
                ('api_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'eSIM order',
                'verbose_name_plural': 'eSIM orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
