# Generated by Django 5.0.2 on 2026-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_esim_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInsuranceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=32, unique=True)),
                ('contract_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('plan_id', models.IntegerField(blank=True, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=200)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('residence_country', models.CharField(blank=True, max_length=3)),
                ('destination_country', models.CharField(blank=True, max_length=3)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('till_date', models.DateField(blank=True, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('customer_address', models.CharField(blank=True, max_length=300)),
                ('travellers_json', models.JSONField(blank=True, default=list)),
                ('api_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Travel insurance order',
                'verbose_name_plural': 'Travel insurance orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
