# Generated by Django 5.0.2 on 2026-08-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_travel_insurance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='available_from',
            field=models.DateField(blank=True, help_text='First date this package is available', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='available_to',
            field=models.DateField(blank=True, help_text='Last date this package is available', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='excluded',
            field=models.TextField(blank=True, help_text='What is not included — one item per line'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='excluded_ar',
            field=models.TextField(blank=True, help_text='What is not included — one item per line', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='excluded_en',
            field=models.TextField(blank=True, help_text='What is not included — one item per line', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='excluded_fr',
            field=models.TextField(blank=True, help_text='What is not included — one item per line', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='included',
            field=models.TextField(blank=True, help_text='What is included — one item per line'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='included_ar',
            field=models.TextField(blank=True, help_text='What is included — one item per line', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='included_en',
            field=models.TextField(blank=True, help_text='What is included — one item per line', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='included_fr',
            field=models.TextField(blank=True, help_text='What is included — one item per line', null=True),
        ),
    ]
